MODEL:
  TYPE: vit
  NAME: pretrain
  DROP_PATH_RATE: 0.0
  RECOVER_TARGET_TYPE: normal
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    INIT_VALUES: None
    USE_APE: True
    USE_RPB: False
    USE_SHARED_RPB: False
    USE_MEAN_POOLING: False
DATA:
  IMG_SIZE: 224
  FILTER_TYPE: mfm
  SAMPLE_RATIO: 0.5
  MASK_RADIUS1: 64
  MASK_RADIUS2: 999
TRAIN:
  WEIGHT_DECAY: 0.05
  OPTIMIZER:
    BETAS: (0.9, 0.95)
PRINT_FREQ: 100
SAVE_FREQ: 1
TAG: mfm_pretrain__vit_base__img224__300ep
